# Generated by Django 5.1.1 on 2024-10-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0003_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
